version: '3'

services:
  web:
    build: ./web
    container_name: web
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootps
      MYSQL_DATABASE: LaravelDB
      MYSQL_USER: develop
      MYSQL_PASSWORD: developps